import React from "react";

function ContrastHeroImage({ colors }) {
  return (
    <div>
      <svg
        width="100%"
        height="100%"
        viewBox="0 0 500 500"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          x="10"
          y="10"
          width="250"
          height="47"
          rx="6"
          fill={colors.primary}
        />
        <rect
          x="342"
          y="188"
          width="148"
          height="47"
          rx="6"
          fill={colors.accent}
        />
        <rect
          x="268"
          y="188"
          width="64"
          height="47"
          rx="6"
          fill={colors.text}
        />
        <rect
          x="268"
          y="367"
          width="222"
          height="47"
          rx="6"
          fill={colors.primary}
        />
        <rect
          x="10"
          y="424"
          width="480"
          height="66"
          rx="6"
          fill={colors.secondary}
        />
        <rect
          x="10"
          y="67"
          width="122"
          height="111"
          rx="6"
          fill={colors.accent}
        />
        <rect
          x="10"
          y="188"
          width="248"
          height="226"
          rx="6"
          fill={colors.primary}
        />
        <rect
          x="142"
          y="67"
          width="116"
          height="111"
          rx="6"
          fill={colors.secondary}
        />
        <rect
          x="268"
          y="245"
          width="222"
          height="112"
          rx="6"
          fill={colors.text}
        />
        <rect
          x="268"
          y="10"
          width="103"
          height="168"
          rx="6"
          fill={colors.secondary}
        />
        <rect
          x="381"
          y="10"
          width="109"
          height="168"
          rx="6"
          fill={colors.primary}
        />
      </svg>
    </div>
  );
}

export default ContrastHeroImage;
